Algoritmo "conversão"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2022
Var
// Seção de Declarações das variáveis 
    reais, dolares: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Quantos reais eu tenho ? ")
    leia (reais)
    dolares <- reais/4
    escreva("Posso ter  ",dolares)

Fimalgoritmo