Algoritmo "Emprestimo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/05/2022
Var
// Seção de Declarações das variáveis 
    emprestimo, juros : Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreva ("Qual o valor do emprestimo ? ")
    leia (emprestimo)
    juros <- (emprestimo * 20)/100
    Escreva ("O valor do emprestimo ficara ", juros)

Fimalgoritmo