Algoritmo "preçodoimposto"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/05/2022
Var
// Seção de Declarações das variáveis 
       imposto, preco : Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       Escreva ("Qual o preço do produto ? ")
       leia(preco)
       imposto <- (preco * 60)/100
       Escreva ("O valor do imposto e ",imposto)

Fimalgoritmo