Algoritmo "seno"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2022
Var
// Seção de Declarações das variáveis 
       angulo, s:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva("informe um angulo :")
       leia (angulo)
       s <- sen(grauprad(angulo))
       escreva ("O seno de ", angulo ," e igual a ", s)
       

Fimalgoritmo