Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2022
Var
// Seção de Declarações das variáveis 
        n1, n2, s :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        escreva("Digite o numero : ")
        leia(n1)
        escreva("Digite outro numero : ")
        leia(n2)
        s <- n1+n2
        escreva("A soma e ",s)

Fimalgoritmo